


   events {}
   http {
       include /etc/nginx/mime.types;   # يتم تضمينه مرة واحدة فقط هنا

       server {
           listen 80;
           root /usr/share/nginx/html;
           index index.html;

           location / {
               try_files $uri $uri/ /index.html;
           }
       }
   }
