/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SalleTp } from '../../models/salle-tp';

export interface GetSalleTpById$Params {
  id: number;
}

export function getSalleTpById(http: HttpClient, rootUrl: string, params: GetSalleTpById$Params, context?: HttpContext): Observable<StrictHttpResponse<SalleTp>> {
  const rb = new RequestBuilder(rootUrl, getSalleTpById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SalleTp>;
    })
  );
}

getSalleTpById.PATH = '/salle-tps/{id}';
