/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Commande } from '../../models/commande';

export interface CreateCommande$Params {
      body: Commande
}

export function createCommande(http: HttpClient, rootUrl: string, params: CreateCommande$Params, context?: HttpContext): Observable<StrictHttpResponse<Commande>> {
  const rb = new RequestBuilder(rootUrl, createCommande.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Commande>;
    })
  );
}

createCommande.PATH = '/commandes';
