/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Commande } from '../../models/commande';

export interface UpdateCommande$Params {
  id: string;
      body: Commande
}

export function updateCommande(http: HttpClient, rootUrl: string, params: UpdateCommande$Params, context?: HttpContext): Observable<StrictHttpResponse<Commande>> {
  const rb = new RequestBuilder(rootUrl, updateCommande.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Commande>;
    })
  );
}

updateCommande.PATH = '/commandes/{id}';
