/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Preparation } from '../../models/preparation';

export interface CreatePreparation$Params {
      body: Preparation
}

export function createPreparation(http: HttpClient, rootUrl: string, params: CreatePreparation$Params, context?: HttpContext): Observable<StrictHttpResponse<Preparation>> {
  const rb = new RequestBuilder(rootUrl, createPreparation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Preparation>;
    })
  );
}

createPreparation.PATH = '/preparations';
