/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Produit } from '../../models/produit';

export interface UpdateProduit$Params {
  id: number;
      body: Produit
}

export function updateProduit(http: HttpClient, rootUrl: string, params: UpdateProduit$Params, context?: HttpContext): Observable<StrictHttpResponse<Produit>> {
  const rb = new RequestBuilder(rootUrl, updateProduit.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Produit>;
    })
  );
}

updateProduit.PATH = '/produits/{id}';
