/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Produit } from '../models/produit';
export interface Armoire {
  designation?: string;
  id?: number;
  produits?: Array<Produit>;
}
