/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Fournisseur } from '../models/fournisseur';
import { ProduitCommande } from '../models/produit-commande';
import { User } from '../models/user';
export interface Commande {
  createdDate?: string;
  date?: string;
  designation?: string;
  fournisseur?: Fournisseur;
  id?: number;
  lastModifiedDate?: string;
  numero?: string;
  observation?: string;
  produits?: Array<ProduitCommande>;
  user?: User;
}
