/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Commande } from '../models/commande';
export interface Fournisseur {
  adresse?: string;
  commandes?: Array<Commande>;
  email?: string;
  id?: number;
  nmrTel?: string;
  nom?: string;
}
