/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Inventaire {
  anneeScolaire?: string;
  commentaire?: string;
  createdDate?: string;
  date?: string;
  id?: number;
  lastModifiedDate?: string;
  quantiteRestante?: number;
  responsable?: string;
}
