/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Post {
  content?: string;
  createdDate?: string;
  date?: string;
  id?: number;
  lastModifiedDate?: string;
  title?: string;
}
