/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PreparationTp } from '../models/preparation-tp';
import { Produit } from '../models/produit';
export interface Preparation {
  createdDate?: string;
  date?: string;
  designation?: string;
  id?: number;
  lastModifiedDate?: string;
  preparationTPs?: Array<PreparationTp>;
  produit1?: Produit;
  produit2?: Produit;
  quantite?: number;
  quantite1?: number;
  quantite2?: number;
}
