/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Preparation } from '../models/preparation';
export interface PreparationTp {
  id?: number;
  preparation?: Preparation;
  quantite?: number;
}
