/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Produit } from '../models/produit';
export interface ProduitTp {
  id?: number;
  produit?: Produit;
  quantite?: number;
}
