/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Produit } from '../models/produit';
export interface ProduitCommande {
  id?: number;
  produit?: Produit;
  quantiteAjoutee?: number;
}
