/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Role {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: 'ADMINISTRATEUR' | 'PROFFESSEUR' | 'PREPARATEUR' | 'DIRECTEUR' | 'USER';
}
