/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Armoire } from '../models/armoire';
export interface SalleTp {
  armoires?: Array<Armoire>;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  numero?: string;
}
