/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PreparationTp } from '../models/preparation-tp';
import { ProduitTp } from '../models/produit-tp';
import { SalleTp } from '../models/salle-tp';
import { User } from '../models/user';
export interface Tp {
  createdDate?: string;
  id?: number;
  jourTp?: string;
  lastModifiedDate?: string;
  niveauScolaire?: 'NIVEAU_1' | 'NIVEAU_2' | 'NIVEAU_3' | 'NIVEAU_4' | 'NIVEAU_7' | 'NIVEAU_8' | 'NIVEAU_9';
  preparations?: Array<PreparationTp>;
  produits?: Array<ProduitTp>;
  prof?: User;
  salleTp?: SalleTp;
  type?: 'CHIMIE' | 'PHYSIQUE' | 'INFORMATIQUE' | 'TECHNIQUE';
}
