/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Fournisseur } from '../../models/fournisseur';

export interface GetFournisseurById$Params {
  id: number;
}

export function getFournisseurById(http: HttpClient, rootUrl: string, params: GetFournisseurById$Params, context?: HttpContext): Observable<StrictHttpResponse<Fournisseur>> {
  const rb = new RequestBuilder(rootUrl, getFournisseurById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Fournisseur>;
    })
  );
}

getFournisseurById.PATH = '/fournisseurs/{id}';
