/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Tp } from '../../models/tp';

export interface GetTpById$Params {
  id: number;
}

export function getTpById(http: HttpClient, rootUrl: string, params: GetTpById$Params, context?: HttpContext): Observable<StrictHttpResponse<Tp>> {
  const rb = new RequestBuilder(rootUrl, getTpById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Tp>;
    })
  );
}

getTpById.PATH = '/tps/{id}';
