/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Labo } from '../../models/labo';

export interface CreateLabo$Params {
      body: Labo
}

export function createLabo(http: HttpClient, rootUrl: string, params: CreateLabo$Params, context?: HttpContext): Observable<StrictHttpResponse<Labo>> {
  const rb = new RequestBuilder(rootUrl, createLabo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Labo>;
    })
  );
}

createLabo.PATH = '/labos';
