/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Labo } from '../../models/labo';

export interface UpdateLabo$Params {
  id: string;
      body: Labo
}

export function updateLabo(http: HttpClient, rootUrl: string, params: UpdateLabo$Params, context?: HttpContext): Observable<StrictHttpResponse<Labo>> {
  const rb = new RequestBuilder(rootUrl, updateLabo.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Labo>;
    })
  );
}

updateLabo.PATH = '/labos/{id}';
