/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Armoire } from '../../models/armoire';

export interface GetAllArmoires$Params {
}

export function getAllArmoires(http: HttpClient, rootUrl: string, params?: GetAllArmoires$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Armoire>>> {
  const rb = new RequestBuilder(rootUrl, getAllArmoires.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Armoire>>;
    })
  );
}

getAllArmoires.PATH = '/armoires';
