/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Armoire } from '../../models/armoire';

export interface GetArmoireById$Params {
  id: number;
}

export function getArmoireById(http: HttpClient, rootUrl: string, params: GetArmoireById$Params, context?: HttpContext): Observable<StrictHttpResponse<Armoire>> {
  const rb = new RequestBuilder(rootUrl, getArmoireById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Armoire>;
    })
  );
}

getArmoireById.PATH = '/armoires/{id}';
