/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Armoire } from './models/armoire';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Commande } from './models/commande';
export type { Fournisseur } from './models/fournisseur';
export type { GrantedAuthority } from './models/granted-authority';
export type { Inventaire } from './models/inventaire';
export type { Labo } from './models/labo';
export type { Post } from './models/post';
export type { Preparation } from './models/preparation';
export type { PreparationTp } from './models/preparation-tp';
export type { Produit } from './models/produit';
export type { ProduitCommande } from './models/produit-commande';
export type { ProduitTp } from './models/produit-tp';
export type { RegistrationRequest } from './models/registration-request';
export type { Role } from './models/role';
export type { SalleTp } from './models/salle-tp';
export type { Tp } from './models/tp';
export type { User } from './models/user';
