/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inventaire } from '../../models/inventaire';

export interface GetAllInventaires$Params {
}

export function getAllInventaires(http: HttpClient, rootUrl: string, params?: GetAllInventaires$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Inventaire>>> {
  const rb = new RequestBuilder(rootUrl, getAllInventaires.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Inventaire>>;
    })
  );
}

getAllInventaires.PATH = '/inventaires';
