/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Inventaire } from '../../models/inventaire';

export interface GetInventaireById$Params {
  id: number;
}

export function getInventaireById(http: HttpClient, rootUrl: string, params: GetInventaireById$Params, context?: HttpContext): Observable<StrictHttpResponse<Inventaire>> {
  const rb = new RequestBuilder(rootUrl, getInventaireById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Inventaire>;
    })
  );
}

getInventaireById.PATH = '/inventaires/{id}';
